version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install puppeteer dependencies
          command: 'sh .circleci/setup.sh'
      - run:
          name: Install project dependencies
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm test
